#!/usr/bin/env php
<?php
define('VERZIJA', '0.1');

require "vendor/autoload.php";
require "src/rokenrol.php";

$self = array_shift($argv);
$file = array_shift($argv);

if (empty($file)) {
    echo sprintf('Рокенрол %s'.PHP_EOL, VERZIJA);
    echo sprintf('Први српски православни програмски језик'.PHP_EOL);
    echo PHP_EOL;
    echo sprintf('Коришћење: %s скрипта.рнр [параметар1 [параметар2 [...]]]'.PHP_EOL, $self);
    exit(0);
}

if (!is_file($file)) {
    echo sprintf('Погубна грешка: Скрипта %s није пронађена!'.PHP_EOL, $file);
    exit(1);
}

$parse = new \Avram\Rokenrol\CodeParser();
$runner = new \Avram\Rokenrol\CodeRunner();

$php = $parse->translate(file_get_contents($file));

$runner->assign('скрипта', $file);
$runner->assign('параметри', $argv);
$runner->run($php);
exit(0);