#!/usr/bin/env php
<?php

use Avram\Rokenrol\CodeParser;
use Avram\Rokenrol\CodeRunner;

const VERZIJA = '0.2';

require "vendor/autoload.php";
require "src/rokenrol.php";

$self = array_shift($argv);
$file = array_shift($argv);

if (empty($file)) {
    echo sprintf('Рокенрол %s'.PHP_EOL, VERZIJA);
    echo sprintf('Први српски православни програмски језик'.PHP_EOL);
    echo PHP_EOL;
    echo sprintf('Коришћење: %s скрипта.рнр [параметар1 [параметар2 [...]]]'.PHP_EOL, $self);
    exit(0);
}

if (!is_file($file)) {
    echo sprintf('Погубна грешка: Скрипта %s није пронађена!'.PHP_EOL, $file);
    exit(1);
}

$code   = file_get_contents($file);
$runner = new CodeRunner(new CodeParser());

$runner->assign('скрипта', $file)
    ->assign('параметри', $argv)
    ->run($code);

exit(0);